Low-impact regression test and build system changes:
1. OldCompsetRun is now at the application level.  This is because it
is almost entirely application-specific code.

2. There are two new shell-include files which load the module command
and purge modules.  These are entirely self-contained; they can be
lifted out of the NEMS repository and used independently:

  src/conf/module-setup.csh.inc  - for csh and tcsh
  src/conf/module-setup.sh.inc   - for ksh, sh, and bash

3. The "configure" script generates two scripts that will load NEMS
modules from src/conf:

  src/conf/modules.nems.csh
  src/conf/modules.nems.sh

Each one sources the corresponding module-setup file, and then loads
the "module.nems" module from src/conf.  This allows tcsh users (hi,
Jordan!) to do this:

  source src/conf/modules.nems.csh

Thus fixing a long-standing bug in NEMS.



git-svn-id: https://svnemc.ncep.noaa.gov/projects/nems/trunk@86845 281fb692-3a18-0410-826d-9e847983f365

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -2,6 +2,11 @@
 
 CHOSEN_MODULE="$2"
 
+if [[ ! -d "conf" ]] ; then
+    echo "ERROR: This script must be run from the NEMS/src/conf directory." 1>&2
+    exit 1
+fi
+
 if [[ -z "$CHOSEN_MODULE" ]] ; then 
     echo "WARNING: modulefile was not supplied as the second argument" 1>&2
     echo "If possible, specify a modulefile relative to ../../modulefiles" 1>&2
@@ -10,19 +15,33 @@ fi
 
 # copy_diff_files
 copy_diff_files(){
-  if [[ ! -f $2 ]] ; then
-    set -x
+  if ( ! cmp "$1" "$2" > /dev/null 2>&1 ) ; then
+    set -xue
     cp $1 $2
-    set +x
-  else
-  if [[ `diff $1 $2`"" != "" ]] ; then
-    set -x
-    cp $1 $2
-    set +x
+    set +xue
   else
     echo "confirmed $2"
   fi
-  fi
+}
+
+copy_diff_mod()  {
+    if ( ! cmp "$1" "$2" > /dev/null 2>&1 ) ; then
+	set -xue
+	cp -fp "$1" "$2"
+	set +xue
+    else
+	echo "confirmed $2"
+    fi
+    cat > "$2.sh" <<EOF
+source $( pwd -P )/conf/module-setup.sh.inc
+module use $( pwd -P )/conf
+module load modules.nems
+EOF
+    cat > "$2.csh" <<EOF
+source $( pwd -P )/conf/module-setup.csh.inc
+module use $( pwd -P )/conf
+module load modules.nems
+EOF
 }
 
 #
@@ -34,7 +53,7 @@ if [[ $1 = nmmb_intel_theia ]]; then
      copy_diff_files ../../conf/configure.nems.Theia.intel_nmmb conf/configure.nems
      touch conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_nmmb}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      set +x
      echo "NEMS/NMMB build on Theia using Intel and ESMF v7.0.0"
@@ -43,7 +62,7 @@ elif [[ $1 = nmmb_intel_wcoss ]]; then
      copy_diff_files ../../conf/configure.nems.Wcoss.intel_nmmb conf/configure.nems
      touch conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_700_nmmb}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
      set +x
      echo "NEMS/NMMB build on Wcoss using Intel and ESMF v7.0.0"
@@ -52,7 +71,7 @@ elif [[ $1 = gsm_intel_theia ]]; then
      copy_diff_files ../../conf/configure.nems.Theia.intel_gsm conf/configure.nems
      touch conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_gsm}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      set +x
      echo "NEMS/GSM build on Theia using Intel and ESMF v7.0.0"
@@ -61,17 +80,17 @@ elif [[ $1 = gsm_intel_wcoss ]]; then
      copy_diff_files ../../conf/configure.nems.Wcoss.intel_gsm conf/configure.nems
      touch conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_700_gsm}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
      set +x
      echo "NEMS/GSM build on Wcoss using Intel and ESMF v7.0.0"
 
 elif [[ $1 = gsm_intel_wcoss_c ]]; then
      set -x
-     copy_diff_files ../../modulefiles/wcoss.cray/intel_gsm conf/configure.nems
+     copy_diff_files ../../conf/configure.nems.Wcoss_C.intel_gsm conf/configure.nems
      touch conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.cray/ESMF_700_gsm}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
      set +x
      echo "NEMS/GSM build on Wcoss using Intel and ESMF v7.0.0"
@@ -82,28 +101,28 @@ elif [[ $1 = coupled_intel_wcoss ]]; then
      copy_diff_files ../../conf/configure.nems.Wcoss.intel conf/configure.nems
      copy_diff_files ../../conf/externals.nems.Wcoss conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_NUOPC}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      echo "Coupled NEMS build on Wcoss using Intel and ESMF v7.0.0"
 elif [[ $1 = coupled_intel_gaea ]]; then
      copy_diff_files ../../conf/configure.nems.Gaea.intel conf/configure.nems
      copy_diff_files ../../conf/externals.nems.Gaea conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-gaea/ESMF_NUOPC}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      echo "Coupled NEMS build on Gaea using Intel and ESMF v7.0.0"
 elif [[ $1 = coupled_intel_theia ]]; then
      copy_diff_files ../../conf/configure.nems.Theia.intel conf/configure.nems
      copy_diff_files ../../conf/externals.nems.Theia conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_NUOPC}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      echo "Coupled NEMS build on Theia using Intel and ESMF v7.0.0"
 elif [[ $1 = coupled_intel_yellowstone ]]; then
      copy_diff_files ../../conf/configure.nems.Yellowstone.intel conf/configure.nems
      copy_diff_files ../../conf/externals.nems.Yellowstone conf/externals.nems
      CHOSEN_MODULE="${CHOSEN_MODULE:-yellowstone/ESMF_NUOPC}"
-     copy_diff_files "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
      copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
      echo "Coupled NEMS build on Yellowstone using Intel and ESMF v7.0.0"
 elif [[ $1 = coupled_linux_gnu ]]; then
