Updates to NEMS to support FV3 work:
1. NEMSAppBuilder can build the FV3

2. produtil external is updated to produtil v. 4.1

3. The NEMS/src/configure script is updated so that the
application-level custom compilation scripts can specify all four of
the NEMS/src/conf files by specifying a path.  That means the bulky
"if" statement inside the configure script no longer needs to be
updated when the application-level configure files change.

4. Add support for building and testing on WCOSS Cray

5. Workarounds for Luna module purging issues that users have
encountered over the last week or so (see
NEMS/src/conf/module-setup.*.inc)




git-svn-id: https://svnemc.ncep.noaa.gov/projects/nems/trunk@89249 281fb692-3a18-0410-826d-9e847983f365

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1,19 +1,47 @@
 #!/bin/ksh
+set -x
+CONF_OPTION="$1"
+unset CONF_FILE
+CHOSEN_MODULE="${2:-}"
+EXTERNALS_NEMS="${3:-}"
+ESMF_VERSION_DEFINE="${4:-}"
 
-CHOSEN_MODULE="$2"
+if [[ -d NEMS/src/conf ]] ; then
+    cd NEMS/src
+elif [[ -d src/conf ]] ; then
+    cd src
+elif [[ -d ../conf ]] ; then
+    cd ..
+fi
 
-if [[ ! -d "conf" ]] ; then
-    echo "ERROR: This script must be run from the NEMS/src/conf directory." 1>&2
+if [[ ! -d conf ]] ; then
+    echo "ERROR: This script must be run from the NEMS/src directory." 1>&2
     exit 1
 fi
 
-if [[ -z "$CHOSEN_MODULE" ]] ; then 
-    echo "WARNING: modulefile was not supplied as the second argument" 1>&2
-    echo "If possible, specify a modulefile relative to ../../modulefiles" 1>&2
-    echo "I will guess the correct modulefile for you." 1>&2
+if [[ -z "$CONF_OPTION" ]] ; then
+    echo "ERROR: Run with at least one argument:"
+    echo "    ./configure BUILD_NAME"
+    echo "OR: ./configure /path/to/configure.nems [more args]"
+    echo " "
+    echo "Other options:"
+    echo "  \$2 = path to modules.nems"
+    echo "  \$3 = path to externals.nems"
+    echo "  \$4 = path to ESMFVersionDefine.h"
+    exit 1
 fi
 
-# copy_diff_files
+if [[ -z "$CHOSEN_MODULE" ]] ; then
+    echo "no \$2 - Will automatically pick a modulefile"
+fi
+if [[ -z "$ESMF_VERSION_DEFINE" ]] ; then
+    echo "no \$3 - Will automatically pick an ESMFVersionDefine.h"
+    ESMF_VERSION_DEFINE=ESMFVersionDefine_ESMF_NUOPC.h
+fi
+if [[ -z "$EXTERNALS_NEMS" ]] ; then
+    echo "no \$4 - Will automatically pick an externals.nems file"
+fi
+
 copy_diff_files(){
   if ( ! cmp "$1" "$2" > /dev/null 2>&1 ) ; then
     set -xue
@@ -44,110 +72,77 @@ module load modules.nems
 EOF
 }
 
-#
-# Standard
-#
+case "$CONF_OPTION" in
+    nmmb_intel_theia)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Theia.intel_nmmb}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_nmmb}"
+        ;;
+    nmmb_intel_wcoss)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Wcoss.intel_nmmb}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss/ESMF_700_nmmb}"
+        ;;
+    gsm_intel_theia)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Theia.intel_gsm}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_gsm}"
+        ;;
+    gsm_intel_wcoss)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Wcoss.intel_gsm}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_700_gsm}"
+        ;;
+    gsm_intel_wcoss_c)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Wcoss_C.intel_gsm}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.cray/ESMF_700_gsm}"
+        ;;
+    coupled_intel_wcoss)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Wcoss.intel}"
+        EXTERNALS_NEMS="${EXTERNALS_NEMS:-conf/externals.nems.Wcoss}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_NUOPC}"
+        ;;
+    coupled_intel_gaea)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Gaea.intel}"
+        EXTERNALS_NEMS="${EXTERNALS_NEMS:-conf/externals.nems.Gaea}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-gaea/ESMF_NUOPC}"
+        ;;
+    coupled_intel_theia)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Theia.intel}"
+        EXTERNALS_NEMS="${EXTERNALS_NEMS:-conf/externals.nems.Theia}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-gaea/ESMF_NUOPC}"
+        ;;
+    coupled_intel_yellowstone)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Yellowstone.intel}"
+        EXTERNALS_NEMS="${EXTERNALS_NEMS:-conf/externals.nems.Yellowstone}"
+        CHOSEN_MODULE="${CHOSEN_MODULE:-gaea/ESMF_NUOPC}"
+        ;;
+    coupled_linux_gnu)
+        CONF_FILE="${CONF_FILE:-../../conf/configure.nems.Linux.gnu conf/configure.nems}"
+        EXTERNALS_NEMS="${EXTERNALS_NEMS:-../../conf/externals.nems.Linux.gnu}"
+        ;;
+    *)
+        if [[ -f "../../conf/$CONF_OPTION" ]] ; then
+            CONF_FILE="../../conf/$CONF_OPTION"
+        elif [[ ! -f "$CONF_OPTION" ]] ; then
+            echo "$CONF_OPTION: unknown configuration"
+            exit 1
+        fi
+esac
 
-if [[ $1 = nmmb_intel_theia ]]; then
-     set -x
-     copy_diff_files ../../conf/configure.nems.Theia.intel_nmmb conf/configure.nems
-     touch conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_nmmb}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     set +x
-     echo "NEMS/NMMB build on Theia using Intel and ESMF v7.0.0"
-elif [[ $1 = nmmb_intel_wcoss ]]; then
-     set -x
-     copy_diff_files ../../conf/configure.nems.Wcoss.intel_nmmb conf/configure.nems
-     touch conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_700_nmmb}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
-     set +x
-     echo "NEMS/NMMB build on Wcoss using Intel and ESMF v7.0.0"
-elif [[ $1 = gsm_intel_theia ]]; then
-     set -x
-     copy_diff_files ../../conf/configure.nems.Theia.intel_gsm conf/configure.nems
-     touch conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_700_gsm}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     set +x
-     echo "NEMS/GSM build on Theia using Intel and ESMF v7.0.0"
-elif [[ $1 = gsm_intel_wcoss ]]; then
-     set -x
-     copy_diff_files ../../conf/configure.nems.Wcoss.intel_gsm conf/configure.nems
-     touch conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_700_gsm}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
-     set +x
-     echo "NEMS/GSM build on Wcoss using Intel and ESMF v7.0.0"
-
-elif [[ $1 = gsm_intel_wcoss_c ]]; then
-     set -x
-     copy_diff_files ../../conf/configure.nems.Wcoss_C.intel_gsm conf/configure.nems
-     touch conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.cray/ESMF_700_gsm}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE"      conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h              ESMFVersionDefine.h
-     set +x
-     echo "NEMS/GSM build on Wcoss using Intel and ESMF v7.0.0"
-#
-# Coupled
-#
-elif [[ $1 = coupled_intel_wcoss ]]; then
-     copy_diff_files ../../conf/configure.nems.Wcoss.intel conf/configure.nems
-     copy_diff_files ../../conf/externals.nems.Wcoss conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-wcoss.phase1/ESMF_NUOPC}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     echo "Coupled NEMS build on Wcoss using Intel and ESMF v7.0.0"
-elif [[ $1 = coupled_intel_gaea ]]; then
-     copy_diff_files ../../conf/configure.nems.Gaea.intel conf/configure.nems
-     copy_diff_files ../../conf/externals.nems.Gaea conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-gaea/ESMF_NUOPC}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     echo "Coupled NEMS build on Gaea using Intel and ESMF v7.0.0"
-elif [[ $1 = coupled_intel_theia ]]; then
-     copy_diff_files ../../conf/configure.nems.Theia.intel conf/configure.nems
-     copy_diff_files ../../conf/externals.nems.Theia conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-theia/ESMF_NUOPC}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     echo "Coupled NEMS build on Theia using Intel and ESMF v7.0.0"
-elif [[ $1 = coupled_intel_yellowstone ]]; then
-     copy_diff_files ../../conf/configure.nems.Yellowstone.intel conf/configure.nems
-     copy_diff_files ../../conf/externals.nems.Yellowstone conf/externals.nems
-     CHOSEN_MODULE="${CHOSEN_MODULE:-yellowstone/ESMF_NUOPC}"
-     copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     echo "Coupled NEMS build on Yellowstone using Intel and ESMF v7.0.0"
-elif [[ $1 = coupled_linux_gnu ]]; then
-     copy_diff_files ../../conf/configure.nems.Linux.gnu conf/configure.nems
-     copy_diff_files ../../conf/externals.nems.Linux.gnu conf/externals.nems
-     copy_diff_files ESMFVersionDefine_ESMF_NUOPC.h ESMFVersionDefine.h
-     echo "Coupled NEMS build on Linux using GNU and ESMF v7.0.0"
-
-#
-# help message
-#
-else
-     echo;echo "     Run ./configure with one argument:"
-     echo;
-     echo " 'configure nmmb_intel_wcoss'  : NEMS/NMMB build on Wcoss using Intel and ESMF v7.0.0"
-     echo " 'configure nmmb_intel_theia'  : NEMS/NMMB build on Theia using Intel and ESMF v7.0.0"
-     echo " 'configure gsm_intel_wcoss'   : NEMS/GSM build on Wcoss using Intel and ESMF v7.0.0"
-     echo " 'configure gsm_intel_theia'   : NEMS/GSM build on Theia using Intel and ESMF v7.0.0"
-     echo " 'configure gsm_intel_wcoss_c' : NEMS/GSM build on Crays using Intel and ESMF v7.0.0"
-     echo;
-     echo " 'configure coupled_intel_wcoss'       : Coupled NEMS build on Wcoss using Intel and ESMF v7.0.0"
-     echo " 'configure coupled_intel_gaea'        : Coupled NEMS build on Gaea using Intel and ESMF v7.0.0"
-     echo " 'configure coupled_intel_theia'       : Coupled NEMS build on Theia using Intel and ESMF v7.0.0"
-     echo " 'configure coupled_intel_yellowstone' : Coupled NEMS build on Yellowstone using Intel and ESMF v7.0.0"
-     echo " 'configure coupled_linux_gnu'         : Coupled NEMS build on Linux using GNU and ESMF v7.0.0"
-     echo;
+if [[ -z "$CHOSEN_MODULE" ]] ; then
+    cat<<EOF > modules.empty
+#%Module######################################################################
+# Empty module file for coupled_linux_gnu configuration.
+EOF
+    CHOSEN_MODULE='modules.empty'
 fi
 
+set -ue
+
+copy_diff_files "$CONF_FILE" conf/configure.nems
+if [[ -z "$EXTERNALS_NEMS" ]] ; then
+    if [[ ! -e conf/externals.nems || -s conf/externals.nems ]] ; then
+        cat /dev/null > conf/externals.nems
+    fi
+else
+    copy_diff_files "$EXTERNALS_NEMS" conf/externals.nems
+fi
+copy_diff_mod "../../modulefiles/$CHOSEN_MODULE" conf/modules.nems
+copy_diff_files "$ESMF_VERSION_DEFINE" ESMFVersionDefine.h 
